root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/stravafy"
cmd = "sqlc generate && templ generate && go build -o ./tmp/stravafy ."
delay = 0
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = [ ".*.sql.go", "_templ.go", "internal/database/db.go", "internal/database/models.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql"]
kill_delay = 500
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
